CREATE TABLE races (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  edition TEXT NOT NULL,
  distance_km NUMERIC(6, 2) NOT NULL CHECK (distance_km > 0),
  elevation_gain_m INTEGER NOT NULL CHECK (elevation_gain_m >= 0),
  time_limit_minutes INTEGER NOT NULL CHECK (time_limit_minutes > 0),
  source_url TEXT,
  confidence TEXT NOT NULL CHECK (confidence IN ('official', 'secondary', 'unverified'))
);

CREATE TABLE checkpoints (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  race_id INTEGER NOT NULL REFERENCES races(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  distance_km NUMERIC(6, 2) NOT NULL CHECK (distance_km > 0),
  elapsed_limit_minutes INTEGER NOT NULL CHECK (elapsed_limit_minutes > 0)
);

INSERT INTO races (id, name, edition, distance_km, elevation_gain_m, time_limit_minutes, source_url, confidence) VALUES
  (1, 'NTMF 115', '2026 demo', 115.00, 2800, 1440, NULL, 'unverified'),
  (2, 'Alpine 90', '2026 fictional demo', 90.00, 5200, 1500, NULL, 'unverified'),
  (3, 'Forest 80', '2026 fictional demo', 80.00, 2100, 1020, NULL, 'unverified'),
  (4, 'Coast 100', '2026 fictional demo', 100.00, 1200, 1320, NULL, 'unverified');

INSERT INTO checkpoints (race_id, name, distance_km, elapsed_limit_minutes) VALUES
  (1, 'Cassel', 35.00, 360),
  (1, 'Boeschepe', 74.50, 660),
  (1, 'Mont Noir', 96.00, 1080),
  (2, 'Refuge Bas', 28.00, 390),
  (2, 'Col Est', 54.00, 780),
  (2, 'Lac Haut', 72.00, 1110),
  (3, 'Ravito des Pins', 24.00, 300),
  (3, 'Clairiere Nord', 51.00, 660),
  (3, 'Derniere boucle', 68.00, 870),
  (4, 'Dunes Nord', 32.00, 390),
  (4, 'Cap Ouest', 62.00, 780),
  (4, 'Phare Sud', 84.00, 1080);

SELECT setval(pg_get_serial_sequence('races', 'id'), (SELECT MAX(id) FROM races));
